name: FormInfo
main: jp\mazaicrafty\pmmp\FormInfo\Main
api:
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
version: 1.0
author: MazaiCrafty
authors:
# fuyutsuki, famima65536
depend:
- EconomyAPI
- FormAPI
