name: TempBanUI
main: TempBanUI\Main
api: [3.0.0-ALPHA11]
version: 1.0
author: SonsaYT

commands:
 tban:
  description: "Open TempBanUI"
  permission: use.tban
  
 tcheck:
  description: "Check player status"
  permission: use.tcheck
  
permissions:
 use.tban:
  default: op
  description: Use /tban command
  
 use.tcheck:
  default: op
  description: Use /tcheck command
